import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
// Can be imported from a shared config
const locales = ["en", "ka"];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "React Accelerator",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <Providers>
          <>{children}</>
        </Providers>
      </body>
    </html>
  );
}
